# k8s/file-parser.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-parser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-parser
  template:
    metadata:
      labels:
        app: file-parser
    spec:
      containers:
        - name: file-parser
          image: file-parser:latest
          imagePullPolicy: Never
          env:
            - name: AWS_ACCESS_KEY_ID
              value: test
            - name: AWS_SECRET_ACCESS_KEY
              value: test
            - name: AWS_REGION
              value: eu-west-1
            - name: AWS_ENDPOINT_URL
              value: http://localstack:4566
            - name: SQS_INPUT_QUEUE_NAME
              value: ingestor-parser-queue
            - name: SQS_OUTPUT_QUEUE_NAME
              value: parser-analyzer-queue
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: file-parser
spec:
  selector:
    app: file-parser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080